// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelBackend.Services;

#nullable disable

namespace PadelBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240622040536_db-up")]
    partial class dbup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PadelBackend.Models.Racket.Racket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasMaxLength(20)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Racket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Description = "esta es una descripcion de prueba",
                            Image = "esta es una url",
                            Name = "Racketa 1",
                            Price = 12.19f
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "esta es una descripcion de prueba 2",
                            Image = "esta es una url 2",
                            Name = "Racketa 2",
                            Price = 1922.19f
                        });
                });

            modelBuilder.Entity("PadelBackend.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lautaro@gmail.com",
                            Name = "Lautaro Fernandez",
                            Password = "12345678",
                            UserName = "lauta"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lautaro1@gmail.com",
                            Name = "Lautaro Fernandez",
                            Password = "12345678",
                            UserName = "lauta2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lautaro2@gmail.com",
                            Name = "Lautaro Fernandez",
                            Password = "12345678",
                            UserName = "lauta3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
